name: Execute dou script

on:
  schedule:
    - cron: "0 14 * * 1-5"  # Executa todo dia às 13:00 UTC (ajuste para seu fuso horário)
  workflow_dispatch:  # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Instalar wkhtmltopdf
        run: sudo apt-get install -y wkhtmltopdf

      - name: Criar arquivo .env com variáveis secretas
        run: |
          echo "GEMINI_KEY=${{ secrets.GEMINI_KEY }}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
          echo "RECEIVER_EMAIL=${{ secrets.RECEIVER_EMAIL }}" >> .env
          echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> .env

      - name: Executar o script
        run: python dou.py
